starting-maintainers
blitz-js/fr.blitzjs.com pull request #10
Opened 2021-10-25 01:36 UTC by DothamDTH

2021-10-30 03:07 UTC, emeraldsanto requested changes
Mes commentaires sont plutôt liés à la terminologie technique utilisée cette fois 😃

2021-10-30 03:07 UTC, emeraldsanto commented on app/pages/docs/maintainers.mdx
> +- Les changements semblent-ils corrects ? Assurez-vous qu'il n'y ait pas d'issues évidentes.
```suggestion
Les changements semblent-ils corrects ? Assurez-vous qu'il n'y ait pas de problèmes évidents. 
```

2021-10-30 03:07 UTC, emeraldsanto commented on app/pages/docs/maintainers.mdx
> +- Si applicable, une PR a-t-elle été ouverte pour mettre à jour les documents ?
```suggestion
Si applicable, une PR a-t-elle été ouverte pour mettre à jour la documentation ?
```

2021-10-30 03:07 UTC, emeraldsanto commented on app/pages/docs/maintainers.mdx
> +   régressions dans le code associé.
```suggestion
1. Assurez-vous que le code de la PR fonctionne pleinement et correctement comme prévu et qu'il ne comporte 
   aucune régression.
```

2021-10-30 03:07 UTC, emeraldsanto commented on app/pages/docs/maintainers.mdx
> +      dans les notes de version.
```suggestion
   1. Changez le titre du commit afin qu'il soit publiquement compréhensible - ce texte exact se retrouvera
      dans les notes de version.
```

2021-10-30 03:07 UTC, emeraldsanto commented on app/pages/docs/maintainers.mdx
> +      - `meta` - changement meta interne lié au repo/project Blitz
```suggestion
   2. Ajoutez le type du commit dans la description, entre parenthèses comme ceci 
      `(patch)`. Types de commit :
      - `major` - changement majeur (non compatible avec les versions antérieures)
      - `minor` - ajout de fonctionnalités mineures
      - `patch` - corrections, résolution de bogues, améliorations de performance, etc
      - `newapp` - changements au nouveau schéma d'application
      - `recipe` - changements à une recette Blitz
      - `example` - changement à un exemple d'application
      - `meta` - changement meta interne lié au repo/project Blitz
```

2021-10-30 18:02 UTC, DothamDTH commented
Les changements ont été effectués. J'ai refait un peu le tour du document pour voir s'il y avait autre chose à modifier. À vous de me dire ! ^^

2021-10-31 15:23 UTC, emeraldsanto approved these changes

2021-11-03 15:33 UTC, merged