doc-translations-page-traduction
blitz-js/fr.blitzjs.com pull request #11
Opened 2021-11-03 16:07 UTC by DothamDTH

Premier jet de la petite page des doc translations !

2021-11-03 16:09 UTC, DothamDTH commented
[Aidez-nous à Traduire les Documents Blitz.pdf](https://github.com/blitz-js/fr.blitzjs.com/files/7469025/Aidez-nous.a.Traduire.les.Documents.Blitz.pdf)

2021-11-07 05:10 UTC, Mangiang requested changes

2021-11-07 05:10 UTC, Mangiang commented on app/pages/docs/translations.mdx
> +Blitz.js est utilisé par un grand nombre de personnes dans le monde entier, et nous souhaitons que ces personnes puissent
```suggestion
Blitz.js est utilisé par un grand nombre de personnes dans le monde entier, et nous souhaitons qu'elles puissent
```

2021-11-07 05:10 UTC, Mangiang commented on app/pages/docs/translations.mdx
> +Dans la page [langages](/languages), vous verrez la progression de la traduction
```suggestion
Dans la page des [langues](/languages), vous verrez la progression de la traduction
```

2021-11-07 05:13 UTC, Mangiang approved these changes

2021-11-07 05:13 UTC, merged