feat: added translation of `Tutorial` documentation page
blitz-js/fr.blitzjs.com pull request #6
Opened 2021-10-24 16:10 UTC by emeraldsanto

Voici la traduction de la page "Tutoriel".

J'ai un peu hésité à traduire le code puisque la plupart est auto-générée. J'ai finalement opté pour un juste milieu, c'est à dire seulement traduire ce que l'utilisateur peut changer, mais je ne suis pas certain que ce soit encore parfait.

La page est très longue donc j'ai quelques soucis avec le rendu PDF que je vais essayer de résoudre. Est-ce qu'on pourrait peut-être ajouter un CI pour déployer des previews pour chaque PR de façon à ce que les reviewers puissent facilement voir le résultat?

2021-10-30 02:36 UTC, emeraldsanto commented
J'ai fait une dernière passe pour retourner au texte original dans certains blocs de code, ca devrait être bon maintenant!

2021-10-30 17:37 UTC, DothamDTH requested changes
Il y a essentiellement de petites coquilles ^^ Sinon, dans l'ensemble, ça me paraît bon !

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Prisma fournit par Blitz. Pour débuter, exécutez cette commande :
```suggestion
Prisma fourni par Blitz. Pour débuter, exécutez cette commande :
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +changements ne seront pas nécéssaires mais pour l'instant ils sont requis
```suggestion
changements ne seront pas nécessaires mais pour l'instant, ils sont requis
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +lors de la création des modèles. Ce sera le cas bientôt, mais en
```suggestion
lors de la création des modèles. Ce sera bientôt le cas, mais en
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +composant `QuestionsList` à été généré dans une étape précédente :
```suggestion
composant `QuestionsList` a été généré dans une étape précédente :
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +l'attribut `name` de `Question` mais ce champ n'existe pas! Nous devons
```suggestion
l'attribut `name` de `Question` mais ce champ n'existe pas ! Nous devons
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Pour le moment Prisma ne nous permet pas de supprimer des données en
```suggestion
Pour le moment, Prisma ne nous permet pas de supprimer des données en
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Parfait! Assurez-vous que votre application est démarrée. Si ce n'est pas
```suggestion
Parfait ! Assurez-vous que votre application est démarrée. Si ce n'est pas
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Vous vous débrouillez bien jusqu'ici! Nous avons maintenant besoin
```suggestion
Vous vous débrouillez bien jusqu'ici ! Nous avons maintenant besoin
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +schema zod afin qu'il accepte ces nouveaux choix. Nous devons également
```suggestion
schéma zod afin qu'il accepte ces nouveaux choix. Nous devons également
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +choix. Ensuite, nous devons exporter le schema zod de `CreateQuestion`
```suggestion
choix. Ensuite, nous devons exporter le schéma zod de `CreateQuestion`
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Ensuite nous allons créer un fichier séparé où nous allons stocker la
```suggestion
Ensuite, nous allons créer un fichier séparé où nous allons stocker le
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +schema de validation zod pour `QuestionForm`. Dans le répertoire
```suggestion
schéma de validation zod pour `QuestionForm`. Dans le répertoire
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +l'utiliser dans le schema `QuestionForm` de la prochaine étape.
```suggestion
l'utiliser dans le schéma `QuestionForm` de la prochaine étape.
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +l'utiliser en tant que schema de `QuestionForm`. Nous devons aussi ajouter
```suggestion
l'utiliser en tant que schéma de `QuestionForm`. Nous devons aussi ajouter
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +question à choix multiples!
```suggestion
question à choix multiples !
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +question au même endroit? Premièrement vous devons personnaliser les
```suggestion
question au même endroit ? Premièrement, nous devons personnaliser les
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +**Magie!**
```suggestion
**Magie !**
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Vérifiez le tout en visitant `/questions` avec votre navigateur.
```suggestion
Vérifiez-le tout en visitant `/questions` avec votre navigateur.
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +## Permettez aux utilisateurs de voter! {#let-people-vote-on-questions}
```suggestion
## Permettez aux utilisateurs de voter ! {#let-people-vote-on-questions}
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +ressembler à ceci!
```suggestion
ressembler à ceci !
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +#### Il est temps de voter!
```suggestion
#### Il est temps de voter !
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Premièrement nous devons ouvrir `app/choices/mutations/updateChoice.ts`,
```suggestion
Premièrement, nous devons ouvrir `app/choices/mutations/updateChoice.ts`,
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +modifier le schema zod et ajouter un incrementeur de votes.
```suggestion
modifier le schéma zod et ajouter un incrémenteur de votes.
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Par la suite nous devons modifier l'appel à `useQuery` pour inclure la
```suggestion
Par la suite, nous devons modifier l'appel à `useQuery` pour inclure la
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Finalement, disons à notre nouveau `button` d'exécuter cette fonction!
```suggestion
Finalement, disons à notre nouveau `button` d'exécuter cette fonction !
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Cette partie est donc déjà faite pour nous, il ne reste qu'a modifier
```suggestion
Cette partie est donc déjà faite pour nous, il ne reste qu'à modifier
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +existe déjà, modifiez le. Sinon créez le". C'est parfait pour notre cas de
```suggestion
existe déjà, modifiez-le. Sinon créez-le". C'est parfait pour notre cas de
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +modifier le schema zod `CreateChoice` afin qu'il inclue les champs requis.
```suggestion
modifier le schéma zod `CreateChoice` afin qu'il inclue les champs requis.
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +🥳 Félicitations! Vous avez créé votre propre application Blitz!
```suggestion
🥳 Félicitations ! Vous avez créé votre propre application Blitz !
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +plus votre application de votes? Voici quelques suggestions :
```suggestion
plus votre application de votes ? Voici quelques suggestions :
```

2021-10-30 17:37 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +lien avec les autres membres dans le canal **#built-with-blitz**!
```suggestion
lien avec les autres membres dans le canal **#built-with-blitz** !
```

2021-10-31 15:28 UTC, emeraldsanto commented on app/pages/docs/tutorial.mdx
> +schema de validation zod de `CreateQuestion` afin qu'il utilise `text`
Ah bien vu!

2021-10-31 15:31 UTC, emeraldsanto commented
> Il y a essentiellement de petites coquilles ^^ Sinon, dans l'ensemble, ça me paraît bon !

Merci! Ces fichus points d'exclamation et d'interrogation 😅

2021-11-03 15:26 UTC, DothamDTH requested changes
Désolée d'être aussi pointilleuse ^^", j'ai encore trouvé 3 petites fautes. Je promets que ce sont les derniers changements à faire !

2021-11-03 15:26 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Jettons un oeil à ce que `blitz new` a créé :
```suggestion
Jetons un œil à ce que `blitz new` a créé :
```

2021-11-03 15:26 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +schema de validation zod de `CreateQuestion` afin qu'il utilise `text`
```suggestion
schéma de validation zod de `CreateQuestion` afin qu'il utilise `text`
```

2021-11-03 15:26 UTC, DothamDTH commented on app/pages/docs/tutorial.mdx
> +Si vous cliquez sur le boutton **Modifier** sur la page d'une question
```suggestion
Si vous cliquez sur le bouton **Modifier** sur la page d'une question
```

2021-11-07 13:42 UTC, emeraldsanto commented
> Désolée d'être aussi pointilleuse ^^", j'ai encore trouvé 3 petites fautes. Je promets que ce sont les derniers changements à faire !

En effet on dirait que je suis allé un peu vite sur celles-là 😬

2021-11-07 16:29 UTC, DothamDTH approved these changes
Tout me paraît correct cette fois-ci !

2021-11-07 18:02 UTC, merged